### ISSUE TITLE
Assets will not migrate from existing remote WordPress site

### ISSUE THREAD

**Issue by brigleb** [craftcms/wp-import#11]
### Description

Hello! When I attempt to migrate my WordPress site, all asset migrations fail with the following error:

```
 → Importing media … 
    → Importing media joe-subscription-header2 (27686) … 
       → Creating the Uploads volume … error: A subpath is required for this filesystem.
    error: A subpath is required for this filesystem.
```

This continues to fail for all assets. I’m a bit confused by this because I can upload assets to this test project directly just fine, so I’m not sure what might be amiss, although I am a Craft CMS newbie.

I have this in `config/project/project.yaml` which may be relevant:

```yaml
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: /uploads
```

…and under `config/project/volumes/local-xxx.yaml` this could be relevant:

```yaml
fs: uploads
handle: local
name: Local
sortOrder: 1
subpath: '@webroot/uploads'
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploads
transformSubpath: '@webroot/uploads'
```

### Steps to reproduce

1. Set up the `starter-wordpress` project via DDEV.
2. Set up basic asset uploading and test.
3. Initiate `ddev craft wp-import`, enter credentials, and confirm migration.

### Additional info

- Craft version: 5.6.7
- PHP version: 8.2
- Database driver & version: MySQL 8.0
- Plugins & versions: All that come with https://github.com/craftcms/starter-wordpress by default
