### ISSUE TITLE
Suggestion: Simpler option to allow two DDEV projects to talk to each other

### ISSUE THREAD

**Issue by rungta** [craftcms/wp-import#17]
https://github.com/craftcms/wp-import/blob/ea7beccbb66f347c6594761751826fc0de7591ba/README.md?plain=1#L96-L97

Instead of recommending ngrok, perhaps the docs could suggest the [DDEV recommended way](https://ddev.readthedocs.io/en/stable/users/usage/faq/#features-requirements) to allow two projects on localhost to talk to each other?

1.  In the Craft DDEV project, create the `.ddev/docker-compose.communicate.yaml`
    config file and add a link to the locally hosted WordPress DDEV project (eg: `wp-blog.ddev.site`):
    
    ```yaml
    # Allows connection to a different DDEV project on localhost
    # https://ddev.readthedocs.io/en/stable/users/usage/faq/#communicate-via-https
    services:
      web:
        external_links:
          - "ddev-router:wp-blog.ddev.site"
    ```
    
2.  Restart the Craft DDEV project: `ddev restart`
3. `ddev craft wp-import` should now be able to talk to `http://wp-blog.ddev.site` directly.

Simpler, fewer steps, and no external network requests are involved.
